name: ci-integration

on:
  push:

jobs:
  ci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout stage
        uses: actions/checkout@v4

      - name: Installing the node
        uses: actions/setup-node@v4
        with:
          node-version: '>=10.15.0'

      - name: Installing the dependency
        run: npm install 

      - name: Testing unit of code
        run: CI=true npm test -- --watchAll=false --reporters=default --reporters=jest-junit

      - name: Listing the files
        run: ls

      - uses: actions/upload-artifact@v7
        with:
          name: test-report
          path: reports/junit.xml