name: ci-integration

on:
  push:
  workflow_dispatch: 

jobs:
  ci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout stage
        uses: actions/checkout@v4

      - name: Installing the node
        uses: actions/setup-node@v4
        with:
          node-version: '>=10.15.0'

      - uses: actions/cache@v5
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: node_modules #Folder where dependency are stored
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}


      - name: Installing the dependency
        run: npm install 

      - name: Testing unit of code
        run: CI=true npm test -- --watchAll=false --reporters=default --reporters=jest-junit

      - uses: actions/upload-artifact@v7
        with:
          name: test-report
          path: reports/junit.xml

      - name: running a coverage
        run: npm run coverage

      - name: listing the report
        run: ls -lR